<html><head>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<title>deltasql, Database Evolution under Control</title>
<link rel="stylesheet" type="text/css" href="deltasql/deltasql.css">
</head><body>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-22222509-1");
pageTracker._trackPageview();
} catch(err) {}
</script>

<img src="deltasql/pictures/deltasql.png" border="0">
<h2>deltasql, Database Evolution under Control</h2>

<p>deltasql is an Open Source tool to keep track of your database 
schemas.</p>

<h3>Quick Links</h3>
<ul>
<li><a 
href="http://sourceforge.net/projects/deltasql/files/tutorials%20%28movies%29/" 
target=_blank >Tutorial movies
</a></li>
<li><a href="http://www.deltasql.org/wiki/">Wiki</a></li>
<li><a href="http://www.deltasql.org/deltasql/manual.php">Manual</a></li>
<li><a href="http://www.deltasql.org/deltasql/faq.php">FAQ</a></li>
<li><a href="http://www.deltasql.org/deltasql/">Test deltasql online</a></li>
<li><a href="http://sourceforge.net/projects/deltasql/files/">Download deltasql</a></li>
<li><a href="http://sourceforge.net/projects/deltasql/">Project 
page</a></li>
<li><a href="http://sourceforge.net/p/deltasql/discussion/">Forum</a></li>
</ul>
<center>
<a href="http://sourceforge.net/projects/deltasql/"><img 
src="deltasql/pictures/sourceforge-logo.gif" border="0"></a>
</center>

<h3>Features</h3>
<ul>
<li><img src="deltasql/icons/show.png"> Deltasql server manages SQL scripts which alter database structure 
and contents. 
It  
organizes scripts in modules, which can be grouped in projects. It 
allows to search among them.</li>
<li><img src="deltasql/icons/show2.png"> Database synchronization by adding special synchronization 
table to each schema. Synchronization script generated by deltasql 
server. Handling of branches of branches and tags supported.</li>
<li>Verification step inside synchronization script to ensure 
script is executed on correct schema (available for Oracle and 
PostgreSQL).</li>
<li><img src="deltasql/icons/rights.png"> Several teams of developers can manage several projects and several 
databases.</li>
<li><img src="deltasql/icons/tree.png"> Ability to manage development schemas and production schemas by 
creating branches, branches of branches and tags.</li>
<li>Syncronization scripts can be generated for Oracle, 
postgreSQL, mySQL, Microsoft SQL 
Server and 
sqlite. On user request, any SQL-like database can be supported.</li>
<li>Synchronization script can be exported in several formats, including
 pretty printed HTML, text and XML or even a zipped package with each 
script stored in a file.</li>
<li>Free to use, Open Source tool licensed under GPL.</li>
<li>Integration on Windows platform (XP, 7) with multipurpose 
deltaclient tool.</li>
<li>Integration in Eclipse IDE with ant client or dbredactor 
client.</li>
<li>Bash client can perform <a 
href="deltasql/faq.php#continouus">continouus database 
integration</a> on Linux.</li>
<li>RSS feed and iGoogle Gadget show latest submitted scripts.</li>
<li>Easy to install, like a webforum, as deltasql server runs on 
Apache/PHP backed by a mySQL database.</li>
<li><img src="deltasql/icons/help.png">There is a <a href="deltasql/manual.php">manual</a>,  a <a 
href="deltasql/faq.php">list of frequently asked questions</a> and a set 
of tutorial movies explaining how it works.</li>
<li>It is used productively by companies in Pakistan, USA, Italy, 
Switzerland and India 
and is popular in Japan and South Korea. In some companies it manages 
more than 
2000 scripts and more than 10 projects.</li>
<li>Typically used for large J2EE/Oracle or J2EE/mySQL software architectures which are partially customized to the customer's wishes.</li>
<li>Ability to send email notifications to users who would like to work without deltasql.</li>
<li><a href="deltasql/server_stats.php">Charting</a> features to monitor how deltasql improves over time.</li>
<li>Ability to diff scripts if they were subsequently updated, ability to plot the tree of tags and branches and more...</li>
<li>In short, deltasql is lightweight but powerful, fast and reliable :-)</li>
</ul>
<?php
//<center>
//<script type="text/javascript" src="http://www.ohloh.net/p/10241/widgets/project_users.js?style=red"></script>
//</center>
?>
<h3>How deltasql works</h3>
<p>
A strong version control system for databases saves time to developers, who would like to keep their schema updated while developing with minimal effort. 
With a version control for databases, the number of mistakes dued to different schemas or missing scripts is considerably reduced. Critical errors in production due to schema
 inconsistencies disappear, too.
</p>
<p>
deltasql is an Open Source tool to synchronize databases with source code.
While developing middle size or big applications, developers undertake changes to the data model which go along with changes to the source code. From time
  to time, branches of source code are done to stabilize the code which will go to production. A sort of data model branch is also needed.
</p>
<p>  
deltasql provides a simple set of php scripts to be executed on an apache server backed by a mySQL database to collect all scripts which change the data model, and means to handle 
data model branches. The trick is to number the sql scripts and to create on each database instance a table which keeps the number of the latest executed script 
(the table deltasql uses is named TBSYNCHRONIZE). 
</p>
<p> 
 A <a href="deltasql/dbsync.php">form</a> allows the user to enter data 
from the 
synchronization table and thereafter the needed chain of datamodel updates is computed and shown to the user. The user
 has to manually execute all scripts. It is possible to update development schemas (the HEADs) and production schemas (the branches), to transform a production schema into a development schema and
 vice versa. Also in case of a schema dumped and imported into another database, it is still upgradeable as the synchronization table
 is contained into the copyed schema. However, it is not possible to downgrade a schema back to a previous version. 
</p>
<p> 
 There are <a href="deltasql/index.php">deltasql clients</a>, which automatically collect synchronization data from a given database schema.
 Though deltasql works best with Oracle, PostgreSQL and mySQL schemas, any other database type can use most of deltasql functionality.
</p>
<center>
<script type="text/javascript" src="http://www.ohloh.net/p/10241/widgets/project_basic_stats.js"></script>
</center>
</body></html>
